@baseUrl = http://localhost:4200
@authToken = {{authenticate.response.body.access_token}}
@userId = {{get_all_users.response.body.0.id}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Lucas Coelho",
  "email": "lu@email.com",
  "passwordHash": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "lu@email.com",
  "passwordHash": "123456"
}

###

# @name get_products
GET {{baseUrl}}/products/user/fdafsd
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_products_with_favorites
GET {{baseUrl}}/products/user/{{userId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name delete_user
DELETE {{baseUrl}}/accounts/{{userId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name get_all_users
GET {{baseUrl}}/accounts
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_user
GET {{baseUrl}}/accounts/{{userId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_favorite_list
POST {{baseUrl}}/favorites/{{userId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Lista de Favoritos",
  "description": "Lista de favoritos do Lucas"
}

###

# @name get_favorite_list_user
GET {{baseUrl}}/favorites/{{userId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name add_product_to_favorite_list_1
POST {{baseUrl}}/favorites/{{userId}}/product/0444c4be-1bf4-49eb-a0ea-f42117df5286
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name add_product_to_favorite_list_2
POST {{baseUrl}}/favorites/{{userId}}/product/0d4d86d6-efbc-47c7-8f75-94225a87a81e
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name delete_favorite_list_user
DELETE {{baseUrl}}/favorites/{{userId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name delete_all_products
DELETE {{baseUrl}}/products/
Content-Type: application/json
Authorization: Bearer {{authToken}}
