@baseUrl = http://localhost:4200
@authToken = {{authenticate.response.body.access_token}}
@userId = {{get_all_users.response.body.0.id}}
@productId = {{get_products.response.body.0.id}}
@productId2 = {{get_products.response.body.1.id}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Lucas Coelho",
  "email": "lu@email.com",
  "passwordHash": "123456"
}

###

# @name delete_user
DELETE {{baseUrl}}/accounts/{{userId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "lu@email.com",
  "passwordHash": "123456"
}

###

# @name get_products
GET {{baseUrl}}/products/user/{{userId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name delete_user
DELETE {{baseUrl}}/accounts/{{userId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name delete_all_users
DELETE {{baseUrl}}/accounts
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name get_all_users
GET {{baseUrl}}/accounts
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get_user
GET {{baseUrl}}/accounts/user/{{userId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_favorite_list
POST {{baseUrl}}/favorite/user/{{userId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Lista de Favoritos",
  "description": "Lista de favoritos do Lucas"
}

###

# @name get_favorite_list_user
GET {{baseUrl}}/favorite/user/{{userId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name add_product_to_favorite_list_1
POST {{baseUrl}}/favorite/{{userId}}/product/{{productId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name add_product_to_favorite_list_2
POST {{baseUrl}}/favorite/{{userId}}/product/{{productId2}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name delete_favorite_list_user
DELETE {{baseUrl}}/favorite/{{userId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name delete_all_products
DELETE {{baseUrl}}/products/
Content-Type: application/json
Authorization: Bearer {{authToken}}
