name: Github Continuos Integration
on: [pull_request, push]
jobs:
  run-tests-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup environment
        uses: actions/setup-node@v2
      - name: Install, Build and Test
        run: |
          npm i -g pnpm 
          pnpm install --force --no-frozen-lockfile
          pnpm prisma generate
          pnpm run build
          pnpm test
